### ISSUE TITLE
Errors while migrating from SQlite to Postgresql

### ISSUE THREAD

**Issue by pdenissen** [PaulBratslavsky/reweb-next-strapi-5-example#1]
Hi,

I'm a kinda new to Strapi. I have used this setup and transformed it to a Landing page. All works great.
Now I would like to Dockerize the setup and deploy it on DigitalOcean. For this I would like to Migrate my SQLite database to a Postgresql database. For this I used `pgloader` for Migration.

When starting Strapi with `yarn develop` I'm getting the error:

```
MigrationError: Migration 5.0.0-05-drop-slug-fields-index (up) failed: Original error: select * from information_schema.tables where table_name =     ││   $1 and table_schema = current_schema() - current transaction is aborted, commands ignored until end of transaction block                              ││   at /Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/umzug/lib/umzug.js:169:27                                                                ││   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                         ││   at async Umzug.runCommand (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/umzug/lib/umzug.js:125:20)                                       ││   at async Object.up (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/database/dist/index.js:6510:7)                                  ││   at async Object.up (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/database/dist/index.js:6534:11)                                 ││   at async Object.sync (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/database/dist/index.js:2246:9)                                ││   at async Strapi.bootstrap (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/core/dist/Strapi.js:351:5)                               ││   at async Strapi.load (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/core/dist/Strapi.js:315:5)                                    ││   at async Module.develop (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/strapi/dist/node/develop.js:177:28)                        ││   at async action (/Volumes/2TBSSD/Sites/nomadic-echoes/backend/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)  
```

When checking the output summary from the migration, there are some errors. This is the migration summaray:
```
                                 table name     errors       rows      bytes      total time
-------------------------------------------  ---------  ---------  ---------  --------------
                                      fetch          0          0                     0.000s
                            fetch meta data          0        452                     0.032s
                             Create Schemas          0          0                     0.001s
                           Create SQL Types          0          0                     0.005s
                              Create tables          0        126                     0.120s
                             Set Table OIDs          0         63                     0.003s
-------------------------------------------  ---------  ---------  ---------  --------------
                          strapi_migrations          0          0                     0.017s
                 strapi_migrations_internal          1          0                     0.017s
                 components_layout_top_navs          0          2     0.0 kB          0.021s
                     strapi_database_schema          1          0                     0.022s
              components_layout_price_grids          0          0                     0.029s
                  components_layout_footers          0          2     0.0 kB          0.034s
               components_layout_card_grids          0          2     0.0 kB          0.038s
         components_layout_section_headings          0          0                     0.028s
               components_elements_features          0          0                     0.050s
                   components_layout_heroes          0          4     1.1 kB          0.032s
                 strapi_core_store_settings          0         43   113.2 kB          0.052s
      components_layout_content_with_images          0          0                     0.039s
            components_elements_price_cards          0          0                     0.044s
                  components_elements_cards          0          6     1.2 kB          0.058s
                            strapi_webhooks          0          0                     0.059s
                             upload_folders          0          0                     0.076s
                            strapi_releases          0          0                     0.076s
                                      files          1          0                     0.069s
                           strapi_workflows          0          0                     0.091s
                                i18n_locale          1          0                     0.061s
                             up_permissions          1          0                     0.095s
                     strapi_release_actions          0          0                     0.079s
                                   up_users          1          0                     0.103s
                               globals_cmps          0          4     0.1 kB          0.116s
                    strapi_workflows_stages          0          0                     0.082s
                                   up_roles          1          0                     0.096s
                         landing_pages_cmps          0          4     0.1 kB          0.119s
                                 categories          1          0                     0.100s
                                 pages_cmps          0          4     0.1 kB          0.134s
                                      posts          1          0                     0.133s
                                    globals          1          0                     0.115s
                              landing_pages          1          0                     0.117s
                                      pages          1          0                     0.134s
                                admin_users          1          0                     0.147s
                          strapi_api_tokens          1          0                     0.152s
                          admin_permissions          1          0                     0.135s
                     strapi_transfer_tokens          0          0                     0.164s
            components_layout_top_navs_cmps          0          0                     0.166s
                                admin_roles          1          0                     0.149s
              components_layout_heroes_cmps          0          6     0.2 kB          0.182s
               strapi_api_token_permissions          0          0                     0.151s
          components_layout_card_grids_cmps          0          6     0.2 kB          0.184s
          strapi_transfer_token_permissions          0          0                     0.169s
         components_layout_price_grids_cmps          0          0                     0.164s
                    strapi_history_versions          0          0                     0.196s
             components_layout_footers_cmps          0          2     0.1 kB          0.181s
                           files_folder_lnk          0          0                     0.197s
       components_elements_price_cards_cmps          0          0                     0.186s
         strapi_release_actions_release_lnk          0          0                     0.215s
                          files_related_mph          0         30     1.1 kB          0.198s
    strapi_workflows_stages_permissions_lnk          0          0                     0.213s
                  upload_folders_parent_lnk          0          0                     0.202s
                          up_users_role_lnk          0          1     0.0 kB          0.226s
       strapi_workflows_stages_workflow_lnk          0          0                     0.211s
                 admin_permissions_role_lnk          0        140     1.8 kB          0.233s
                    up_permissions_role_lnk          0         17     0.2 kB          0.220s
                         posts_category_lnk          0          6     0.0 kB          0.223s
     strapi_api_token_permissions_token_lnk          0          0                     0.241s
                      admin_users_roles_lnk          0          1     0.0 kB          0.237s
                  components_elements_links          0         12     0.8 kB          0.247s
strapi_transfer_token_permissions_token_lnk          0          0                     0.240s
       components_layout_music_players_cmps          0          3     0.1 kB          0.254s
            components_layout_music_players          0          2     0.6 kB          0.252s
-------------------------------------------  ---------  ---------  ---------  --------------
                    COPY Threads Completion          0          4                     0.280s
                             Create Indexes          0        229                     0.797s
                     Index Build Completion          0        229                     0.170s
                            Reset Sequences          0         45                     0.017s
                               Primary Keys          0         63                     0.025s
                        Create Foreign Keys         28        132                     0.075s
                            Create Triggers          0          0                     0.000s
                           Install Comments          0          0                     0.000s
-------------------------------------------  ---------  ---------  ---------  --------------
                          Total import time         16        297   121.1 kB          1.364s
```
This is the first time I try to achieve this. But don't really know where to start.

Any idea's on this?

Thank you!

**Comment by pdenissen** [comment]
Ok, just found the solution. I guess it's the best way to set Postgresql as prefered database in `.env` before running the `yarn setup` command. I wasn't aware for the seed-file which imports the demo data into the database which you can set in the `.env`-file.

**Comment by PaulBratslavsky** [comment]
@pdenissen glad you were able to find the solution.
